Update for disabled module
Disabled module have config:
```
[blackfire]
;extension="/usr/local/Cellar/blackfire-php80/1.53.0/blackfire.so"
blackfire.agent_socket = unix:///usr/local/var/run/blackfire-agent.sock
;blackfire.log_level = 3
;blackfire.log_file = /tmp/blackfire.log
```

Now I have error on update:
```
==> Upgrading blackfireio/blackfire/blackfire-php80 1.53.0 -> 1.54.0
==> Downloading https://packages.blackfire.io/homebrew/blackfire-php_1.54.0-darwin_amd64-php80.tar.gz
######################################################################## 100.0%
Error: An exception occurred within a child process:
  Utils::Inreplace::Error: inreplace failed
/usr/local/etc/php/8.0/conf.d/ext-blackfire.ini:
  expected replacement of /^(zend_)?extension=.+$/ with "extension=\"/usr/local/Cellar/blackfire-php80/1.54.0/blackfire.so\""
```